### ISSUE TITLE
FortiOS is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#272]
## The problem

The Home Assistant Device Tracker to support FortiOS integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/fortios/logo.png`
- `src/fortios/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @kimfrellsen! Mind taking a look at this issue as it is with an integration (fortios) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/fortios/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by kimfrellsen** [comment]
Thanks for the notification. I’ll fix that.
/Kim

Den 30. mar. 2020 kl. 20.03 skrev Franck Nijhof <notifications@github.com>:

﻿

The problem

The Home Assistant Device Tracker to support FortiOS integration has
missing brand images.

We recently started this Brands repository, to create a centralized storage
of all brand-related images. These images are used on our website and the
Home Assistant frontend.

The following images are missing and would ideally be added:

   - src/fortios/logo.png
   - src/fortios/logo@2x.png

For image specifications and requirements, please see README.md
<https://github.com/home-assistant/brands/blob/master/README.md>.
Additional information

For more information about this repository, read the README.md
<https://github.com/home-assistant/brands/blob/master/README.md> file of
this repository. It contains information on how this repository works, and
image specification and requirements.
Codeowner mention

Hi there, @kimfrellsen <https://github.com/kimfrellsen>! Mind taking a look
at this issue as it is with an integration (fortios) you are listed as a
codeowner
<https://github.com/home-assistant/core/blob/dev/homeassistant/components/fortios/manifest.json>
for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us
out, feel free to resolve this issue! Thanks already!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/home-assistant/brands/issues/272>, or unsubscribe

**Comment by balloob** [comment]
What's up with this title Frenck?

**Comment by frenck** [comment]
@balloob <https://github.com/home-assistant/core/blob/dev/homeassistant/components/fortios/manifest.json#L3>

Its in the manifest...

**Comment by frenck** [comment]
Opened up a PR to correct the manifest: <https://github.com/home-assistant/core/pull/33454>

**Comment by kimfrellsen** [comment]
A PR with logo files have been created.

**Comment by kimfrellsen** [comment]
https://github.com/home-assistant/brands/pull/845
